"use client";

import React from "react";
import { Meteors } from "../../components/ui/meteors";

import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



function Contact() {
  return (
   <>

    <div className="max-w-[90%]">
    <Meteors number={40} className=" lg:block hidden " />
    </div>
    
    <h1 className=" text-4xl z-49 lg:text-7xl text-white font-bold text-center mt-[150px]">Contact Us</h1>
   <div className="w-[80%]  z-10 text-center mx-auto lg:mt-[40px] mt-[30px] gap-5 space-y-5 ">
      <p className="w-[60%] mx-auto">Lorem ipsum dolor sit amet consectetur adipisicing elit. Eligendi inventore quibusdam sequi? Sint, itaque harum libero debitis dolorum non odit!</p>
    <input placeholder="Your name here" type="text" className="focus:outline-none h-16  bg-gray-800  rounded-lg pl-2  w-full" />

  <textarea id="message" rows={4} className="  p-2 rounded-lg  focus:outline-none  h-[100px] hover:bg-grat-300  bg-gray-800    pl-2  w-full  block" placeholder="Leave a comment..."></textarea>

   </div>
   <div className="w-[80%] mx-auto mt-5 ">
    <button className="bg-blue-500 p-2 z-5 rounded-lg">Send Message</button>
    </div>

    </>
    
  );
}

export default Contact;
